[package]
name = "rsll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.0"
reqwest = "0.12.4"
rodio = "0.18.0"
tokio = { version = "1.37.0", features = ["full"] }
